doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CQRS/User/Domain'
                prefix: 'App\CQRS\User\Domain'

            Stage:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CQRS/Stage/Domain'
                prefix: 'App\CQRS\Stage\Domain'

            Task:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CQRS/Task/Domain'
                prefix: 'App\CQRS\Task\Domain'

            Category:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CQRS/Category/Domain'
                prefix: 'App\CQRS\Category\Domain'

            TaskStep:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CQRS/TaskStep/Domain'
                prefix: 'App\CQRS\TaskStep\Domain'


